### ISSUE TITLE
Hypens in the docker `.env` file breaking config

### ISSUE THREAD

**Issue by switchswap** [MonsterMuffin/rclone-gmedia#1]
I had trouble with the following lines in the `.env` file where `Sonarr` and `Radarr` would mount `GMEDIA` instead of the specific `tv` or `movies` folder and I think it has to do with the hyphens in these variables here:
```
GMEDIA-TV=/mnt/gmedia/tv:/tv
GMEDIA-MOVIE=/mnt/gmedia/movies:/movies
```

Converting them to underscores fixed it for me so I just thought I'd bring it up.

**Comment by monstermuffin** [comment]
Thanks for this, I have updated the .env and docker-compose files to underscores.
